Remove usage of version.LegacyVersion
The "packaging" module has deprecated its LegacyVersion identifier back
in 2020, finally removing it in 2021. This causes cozy to crash when
running against new version of said module, with the following error:
> AttributeError: module 'packaging.version'
>                 has no attribute 'LegacyVersion'